### ISSUE TITLE
document loading error

### ISSUE THREAD

**Issue by seoeaa** [safevideo/autollm#87]
documents = read_files_as_documents(input_dir="examples/data" , recursive=True)

PS D:\Programm\AI\autollm> & C:/Users/Aleksandr/AppData/Local/Programs/Python/Python310/python.exe d:/Programm/AI/autollm/app.py
INFO:autollm.utils.document_reading:Found 1 'documents'.
Parsing documents into nodes: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 69.86it/s]
Generating embeddings:   0%|                                                                                                                                                                           | 0/4 [00:00<?, ?it/s]Embedding Token Usage: 13738
Generating embeddings: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.50it/s] 
Traceback (most recent call last):
  File "d:\Programm\AI\autollm\app.py", line 35, in <module>
    query_engine = AutoQueryEngine.from_parameters(
  File "d:\Programm\AI\autollm\autollm\auto\query_engine.py", line 121, in from_parameters
    return create_query_engine(
  File "d:\Programm\AI\autollm\autollm\auto\query_engine.py", line 43, in create_query_engine
    vector_store_index = AutoVectorStoreIndex.from_defaults(
  File "d:\Programm\AI\autollm\autollm\auto\vector_store_index.py", line 89, in from_defaults
    index = VectorStoreIndex.from_documents(
  File "C:\Users\Aleksandr\AppData\Local\Programs\Python\Python310\lib\site-packages\llama_index\indices\base.py", line 102, in from_documents
    return cls(
  File "C:\Users\Aleksandr\AppData\Local\Programs\Python\Python310\lib\site-packages\llama_index\indices\vector_store\base.py", line 49, in __init__
    super().__init__(
  File "C:\Users\Aleksandr\AppData\Local\Programs\Python\Python310\lib\site-packages\llama_index\indices\base.py", line 71, in __init__
    index_struct = self.build_index_from_nodes(nodes)
  File "C:\Users\Aleksandr\AppData\Local\Programs\Python\Python310\lib\site-packages\llama_index\indices\vector_store\base.py", line 238, in build_index_from_nodes
    return self._build_index_from_nodes(nodes)
  File "C:\Users\Aleksandr\AppData\Local\Programs\Python\Python310\lib\site-packages\llama_index\indices\vector_store\base.py", line 226, in _build_index_from_nodes
    self._add_nodes_to_index(
  File "C:\Users\Aleksandr\AppData\Local\Programs\Python\Python310\lib\site-packages\llama_index\indices\vector_store\base.py", line 187, in _add_nodes_to_index
    new_ids = self._vector_store.add(nodes)
  File "C:\Users\Aleksandr\AppData\Local\Programs\Python\Python310\lib\site-packages\llama_index\vector_stores\lancedb.py", line 122, in add
    tbl.add(data)
  File "C:\Users\Aleksandr\AppData\Local\Programs\Python\Python310\lib\site-packages\lancedb\table.py", line 575, in add
    data = _sanitize_data(
  File "C:\Users\Aleksandr\AppData\Local\Programs\Python\Python310\lib\site-packages\lancedb\table.py", line 69, in _sanitize_data
    data = _sanitize_schema(
  File "C:\Users\Aleksandr\AppData\Local\Programs\Python\Python310\lib\site-packages\lancedb\table.py", line 981, in _sanitize_schema
    [data[name] for name in schema.names], schema=schema
  File "C:\Users\Aleksandr\AppData\Local\Programs\Python\Python310\lib\site-packages\lancedb\table.py", line 981, in <listcomp>
    [data[name] for name in schema.names], schema=schema
  File "pyarrow\table.pxi", line 1538, in pyarrow.lib._Tabular.__getitem__
    return self.column(key)
  File "pyarrow\table.pxi", line 1624, in pyarrow.lib._Tabular.column
    return self._column(self._ensure_integer_index(i))
  File "pyarrow\table.pxi", line 1560, in pyarrow.lib._Tabular._ensure_integer_index
    raise KeyError("Field \"{}\" does not exist in schema"
KeyError: 'Field "original_file_path" does not exist in schema'
Sentry is attempting to send 2 pending events
Waiting up to 2 seconds
Press Ctrl-Break to quit

**Comment by SeeknnDestroy** [comment]
Hi @seoeaa, for a quick fix, you can try to delete your current lancedb database and re-read the documents:

```python
import lancedb

uri = "tmp/lancedb"
table_name = "vectors"
db = lancedb.connect(uri=uri)

db.drop_database()
```

We normally not allowed to load data with different metadata in database tables. That's why you got the error. We will change the behavior of our `read_files_as_documents` to not get different metadatas in different file types. Thank you for bringing this to our attention!

**Comment by SeeknnDestroy** [comment]
Hi @seoeaa,

Thank you for your patience. We've addressed the issue in our latest release. The problem was due to inconsistent metadata fields in the documents being loaded into the database. We've now standardized the metadata fields across different file types to prevent this kind of error in the future.

To resolve the issue on your end, please follow these steps:

1. Update autollm to the latest version: `pip install -U autollm`
2. Remove any existing `lancedb` databases that were created with the old version, as the metadata fields may not be compatible.
3. Re-read the documents using the `read_files_as_documents` function.

Here's a quick snippet to help you clean the old database:

```python
import lancedb

# Provide the correct URI to your lancedb database
uri = "tmp/lancedb"
db = lancedb.connect(uri=uri)

# This will drop the current database so you can start fresh
db.drop_database()
```

After cleaning the database, you can proceed with reading the documents again. If you encounter any further issues or have questions, please don't hesitate to reach out.

Best,
Talha
